name: null
favicon: null
layout_spectrum: 0.6924332533963025
typography_spectrum: 0.40550477453507483
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5019839610904455
  lightness: 0.314570703310892
  saturation: 0.7042895599734038
  rhythmicContrast: 0.4238319213036448
purpose: []
